spring:
  application:
    name: notification-service
  profiles:
    active: default,kafka,mail
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://keycloak.artemis.jirka.test.esnhk.cz/realms/Artemis"
server:
  port: ${SERVER_PORT:8083}
