events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://frontend/;
        }

        location /user-management/ {
            proxy_pass http://user-management-service:${USER_MANAGEMENT_PORT}/;
        }

        location /settings/ {
            proxy_pass http://settings-service:${SETTINGS_SERVICE_PORT}/;
        }
    }
}