events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://frontend:${FRONTEND_PORT}/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /user-management/ {
            proxy_pass http://user-management-service:${USER_MANAGEMENT_PORT}/;
        }

        location /settings/ {
            proxy_pass http://settings-service:${SETTINGS_SERVICE_PORT}/;
        }
    }
}