FROM node:20-alpine
WORKDIR /app

COPY frontend ./frontend
WORKDIR /app/frontend

# Install deps only once
COPY package*.json ./
RUN npm install

# Copy source (you’ll override this with a volume mount)
COPY . .

# Vite dev server (listen on 80, the default exposed port that nginx proxys to)
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]