FROM node:20-alpine
WORKDIR /app

# set env variables
ARG VITE_API_BASE_URL
ARG VITE_KEYCLOAK_URL
ARG VITE_KEYCLOAK_REALM
ARG VITE_KEYCLOAK_CLIENT_ID
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_KEYCLOAK_URL=$VITE_KEYCLOAK_URL
ENV VITE_KEYCLOAK_REALM=$VITE_KEYCLOAK_REALM
ENV VITE_KEYCLOAK_CLIENT_ID=$VITE_KEYCLOAK_CLIENT_ID

COPY frontend ./frontend
WORKDIR /app/frontend

# Install deps only once
COPY package*.json ./
RUN npm install

# Copy source (you’ll override this with a volume mount)
COPY . .

# Vite dev server
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]