server {
    listen 80;

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri.html /200.html;   # .html is for prerendered pages; fallback to 200.html to let SPA handle routing (js)
    }
}