services:

  gateway:
    image: nginx:alpine
    container_name: api-gateway
    command: /bin/sh -c "envsubst '$$USER_MANAGEMENT_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    volumes:
      - ./devops/nginx.conf:/etc/nginx/nginx.conf.template:ro
    environment:
      - USER_MANAGEMENT_PORT=${USER_MANAGEMENT_PORT}
    ports:
      - "${GATEWAY_PORT}:80"
    depends_on:
      - user-management-service

  artemis-database:
    build:
      context: .
      dockerfile: devops/Dockerfile
    container_name: artemis-database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DB_NAMES=${DB_NAMES}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data


  user-management-service:
    build:
      context: .
      dockerfile: usermanagement/Dockerfile
    container_name: user-management-service
    ports:
      - "${USER_MANAGEMENT_PORT}:${USER_MANAGEMENT_PORT}"
    environment:
      - SERVER_PORT=${USER_MANAGEMENT_PORT}
      - DB_HOST=artemis-database
      - DB_PORT=5432
      - DB_NAME=user_management_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      - artemis-database

volumes:
  db-data: