local-student.default-role=BUDDY
local-student.default-assigned-students-capacity=5
international-student.default-role=INTERNATIONAL_STUDENT
profile-pictures.upload-dir=/data/profile-pictures
profile-pictures.size-limit-megabytes=5