openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
paths:


components:
  schemas:
    HealthCheckResponse:
      type: object
      properties:
        status:
          type: string
          example: OK
    RegisterLocalStudentRequest:
      type: object
      required:
        - email
        - password
        - firstName
        - lastName
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    RegisterLocalStudentResponse:
      type: object
      properties:
        result:
          type: string
          example: Student registered successfully

  securitySchemes:
    keycloak_auth:
      type: oauth2
      description: OAuth2 flow via Keycloak
      flows:
        authorizationCode:
          authorizationUrl: https://keycloak.artemis.jirka.test.esnhk.cz/realms/Artemis/protocol/openid-connect/auth
          tokenUrl: https://keycloak.artemis.jirka.test.esnhk.cz/realms/Artemis/protocol/openid-connect/token
          scopes:
            ADMIN: Full administrative access
            USER: Standard user access
            TUTOR: Tutor-level access