openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
paths:


components:
    schemas:
      HealthCheckResponse:
        type: object
        properties:
          status:
            type: string
            example: OK