openapi: 3.0.3
info:
  title: Artemis API
  version: 0.0.1
  description: Artemis API
servers: [ ]
paths:
  /health:
    get:
      tags: [ NotificationService ]
      summary: healthCheck
      description: healthCheck endpoint to verify if the API is running
      operationId: getHealthCheck
      security: [ ]  # no auth required
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'

components:
  schemas:
    HealthCheckResponse:
      type: object
      properties:
        status:
          type: string
          example: "OK"

  securitySchemes:
    keycloak_auth:
      type: oauth2
      description: OAuth2 flow via Keycloak
      flows:
        authorizationCode:
          authorizationUrl: https://keycloak.artemis.jirka.test.esnhk.cz/realms/Artemis/protocol/openid-connect/auth
          tokenUrl: https://keycloak.artemis.jirka.test.esnhk.cz/realms/Artemis/protocol/openid-connect/token
          scopes:
            ADMIN: Full administrative access
            USER: Standard user access
            TUTOR: Tutor-level access