openapi: 3.0.3
info:
  title: Artemis API
  version: 0.0.1
  description: Artemis API
servers:
  - url: /api
paths:
  /health:
    get:
      tags: [ UserManagement ]
      summary: healthCheck
      description: healthCheck endpoint to verify if the API is running
      operationId: getHealthCheck
      #security: []  # no auth required
      security:
        - keycloak_auth: [ TUTOR, ADMIN ]
      x-security-roles:
        - ADMIN
        - TUTOR
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                $ref: './api-components.yaml#/components/schemas/HealthCheckResponse'

  /local-student/register:
    post:
      tags: [ UserManagement ]
      summary: registerLocalStudent
      description: registerLocalStudent endpoint to register a new local student
      operationId: registerLocalStudent
      security: [ ]  # no auth required
      requestBody:
        description: Local student registration details
        required: true
        content:
          application/json:
            schema:
              $ref: './api-components.yaml#/components/schemas/RegisterLocalStudentRequest'
      responses:
        '200':
          description: Student registered successfully
          content:
            application/json:
              schema:
                $ref: './api-components.yaml#/components/schemas/RegisterLocalStudentResponse'
