openapi: 3.0.3
info:
  title: Artemis API
  version: 0.0.1
  description: Artemis API
servers: []
paths:
  /health:
    get:
      tags: [ UserManagement ]
      summary: healthCheck
      description: healthCheck endpoint to verify if the API is running
      operationId: getHealthCheck
      security: [ ]  # no auth required
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'

  /local-student/register:
    post:
      tags: [ UserManagement ]
      summary: registerLocalStudent
      description: registerLocalStudent endpoint to register a new local student
      operationId: registerLocalStudent
      security: [ ]  # no auth required
      requestBody:
        description: Local student registration details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterLocalStudentRequest'
      responses:
        '200':
          description: Student registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterLocalStudentResponse'
  /local-student/{localStudentId}/profile-details:
    parameters:
      - name: localStudentId
        in: path
        description: ID of the local student
        required: true
        schema:
          type: string
          format: uuid
    post:
      tags: [ UserManagement ]
      summary: Complete local student profile details
      description: Allows a registered and approved local student to complete their profile details.
      operationId: completeLocalStudentProfile
      security:
        - keycloak_auth: [ TUTOR, ADMIN ]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LocalStudentProfileDetailsRequest'
      responses:
        '200':
          description: Profile details updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocalStudentProfileDetailsResponse'

        '400':
          description: Bad request (invalid data)
        '401':
          description: Unauthorized

  /international-student/register:
    post:
      tags: [ UserManagement ]
      summary: registerInternationalStudent
      description: Register a new international student
      operationId: registerInternationalStudent
      requestBody:
        description: International student registration details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterInternationalStudentRequest'
      responses:
        '200':
          description: Student registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterInternationalStudentResponse'
  /international-student/{internationalStudentId}/profile-details:
    parameters:
      - name: internationalStudentId
        in: path
        description: ID of the international student
        required: true
        schema:
          type: string
          format: uuid
    post:
      tags: [ UserManagement ]
      summary: Complete international student profile details
      description: Allows a registered and approved international student to complete their profile details.
      operationId: completeInternationalStudentProfile
      security:
        - keycloak_auth: [ TUTOR, ADMIN ]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/InternationalStudentProfileDetailsRequest'
      responses:
        '200':
          description: Profile details updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternationalStudentProfileDetailsResponse'

        '400':
          description: Bad request (invalid data)
        '401':
          description: Unauthorized

components:
  schemas:
    HealthCheckResponse:
      type: object
      properties:
        status:
          type: string
          example: OK

    # A gender enum reused
    GenderEnum:
      type: string
      enum: [MALE, FEMALE, OTHER]

    # Common base schema for students
    StudentBase:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
          pattern: '^\+?[1-9]\d{1,14}$'
        bio:
          type: string
        favouriteActivities:
          type: array
          items:
            type: string
        profilePicturePath:
          type: string
        emailMarketingChecked:
          type: boolean

    # Local student registration schema
    RegisterLocalStudentRequest:
      allOf:
        - $ref: '#/components/schemas/StudentBase'
        - type: object
          properties:
            facultyId:
              type: string
            dateOfBirth:
              type: string
              format: date
            gender:
              $ref: '#/components/schemas/GenderEnum'
            termsAndConditionsChecked:
              type: boolean
            password:
              type: string
          required:
            - firstName
            - lastName
            - email
            - password
            - dateOfBirth
            - phoneNumber
            - gender
            - termsAndConditionsChecked
            - facultyId
    LocalStudentProfileDetailsRequest:
      type: object
      properties:
        facultyId:
          type: string
          description: ID of the faculty
        description:
          type: string
          description: Short student bio
        emailMarketingChecked:
          type: boolean
          description: Consent to receive marketing emails
        profilePicture:
          type: string
          format: binary
          description: Profile picture file
      required:
        - facultyId
        - description
        - emailMarketingChecked
        - profilePicture

    # International student registration schema
    RegisterInternationalStudentRequest:
      allOf:
        - $ref: '#/components/schemas/StudentBase'
        - type: object
          properties:
            countryISO:
              type: string
              pattern: '^[A-Z]{2}$'
            homeUniversity:
              type: string
            facultyId:
              type: string
            accommodationId:
              type: string
            dateOfBirth:
              type: string
              format: date
            gender:
              $ref: '#/components/schemas/GenderEnum'
            termsAndConditionsChecked:
              type: boolean
            password:
              type: string
          required:
            - firstName
            - lastName
            - email
            - password
            - dateOfBirth
            - phoneNumber
            - gender
            - termsAndConditionsChecked

    InternationalStudentProfileDetailsRequest:
      type: object
      properties:
        homeUniversity:
          type: string
          description: Name of the home university
        accommodation:
          type: string
          description: Accommodation details
        facultyId:
          type: string
          description: ID of the faculty
        description:
          type: string
          description: Short student bio
        emailMarketingChecked:
          type: boolean
          description: Consent to receive marketing emails
        profilePicture:
          type: string
          format: binary
          description: Profile picture file
      required:
        - facultyId
        - description
        - emailMarketingChecked
        - profilePicture

    # Responses
    RegisterLocalStudentResponse:
      type: object
      properties:
        result:
          type: string
          example: Student registered successfully

    RegisterInternationalStudentResponse:
      type: object
      properties:
        result:
          type: string
          example: Student registered successfully

    LocalStudentProfileDetailsResponse:
      type: object
      properties:
        result:
          type: string
          example: Profile details updated successfully

    InternationalStudentProfileDetailsResponse:
      type: object
      properties:
        result:
          type: string
          example: Profile details updated successfully

  securitySchemes:
    keycloak_auth:
      type: oauth2
      description: OAuth2 flow via Keycloak
      flows:
        authorizationCode:
          authorizationUrl: https://keycloak.artemis.jirka.test.esnhk.cz/realms/Artemis/protocol/openid-connect/auth
          tokenUrl: https://keycloak.artemis.jirka.test.esnhk.cz/realms/Artemis/protocol/openid-connect/token
          scopes:
            ADMIN: Full administrative access
            USER: Standard user access
            TUTOR: Tutor-level access